services:
  job-service:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: job-service

    env_file:
      - .env

    ports:
      - "${PORT}:${PORT}"

    restart: unless-stopped

    extra_hosts:
      - "host.docker.internal:host-gateway"