services:
  job-service:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: job-service

    env_file:
      - .env

    ports:
      - "${PORT}:${PORT}"

    restart: unless-stopped

    extra_hosts:
      - "host.docker.internal:host-gateway"

    networks:
      - maintenance-net
      - service-registry-network

networks:
  maintenance-net:
    external: true

  service-registry-network:
    external: true
    name: maintenance-service_default