spring:
  application:
    name: job-service
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: ${DATABASE_URL}
    driver-class-name: org.postgresql.Driver
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true

server:
  port: ${PORT}

eureka:
  instance:
    status-page-url-path: /actuator/info
    health-check-url-path: /actuator/health
    prefer-ip-address: true
    ip-address: 192.168.1.200
    non-secure-port: ${PORT}
  client:
    healthcheck:
      enabled: false
    service-url:
      defaultZone: ${EUREKA_URL}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus